### ISSUE TITLE
Fibonacci example

### ISSUE THREAD

**Issue by silviabonfanti** [uasm/uasm-language-examples#1]
I have a question about Fibonacci example (uasm-language-examples/Fibonacci.uasm).

In the derived function **fibo_d(x)** there is the ReturnTerm. ReturnTerm is defined as follows:
**ReturnTerm ::= 'return' VariableTerm 'in' Rule**
**VariableTerm ::= IdFunction**
**IdFunction ::= Id**
**Id ::= [_a-zA-Z]?[_a-zA-Z0-9]***
In the example the field _VariableTerm_ is  _fibo_(x). Following the definitions _VariableTerm _shouldn't contain parenthesis (the terminal Id doesn't contains parenthesis). I think that the derived function fibo_b(x) should be:

derived fibo_d(x) = 
    return fibo in 
        if fibo = undef then { 
            if x < 0 then fibo := 0
            else if x < 2 then fibo := x
            else fibo := fibo_d(x-2) + fibo_d(x-1)
        }

**Comment by mstegmaier** [comment]
Actually that was an error in the language definition. I've fixed it.

**Comment by silviabonfanti** [comment]
Ok! thank you
